### ISSUE TITLE
Cleanup only system tasks

### ISSUE THREAD

**Issue by eduardoalvarenga** [stdevel/arsa#10]
Here´s a diff to allow only system tasks to be archived/deleted. This is very useful if you need only to make thinkgs softer but care for the history of Satellite.
[arsa.diff.txt](https://github.com/stdevel/arsa/files/320814/arsa.diff.txt)

**Comment by stdevel** [comment]
Very good idea, thanks for your contribution! :smiley: 
Merged your code with some other ideas into the latest release 0.4.
